#!/usr/bin/env node
/**
 * @file setup.mjs
 * @description Day-zero Azure/Entra credential setup wizard (`npm run setup`).
 * First interactive CLI script in this project — no existing prompt-library
 * convention to follow, so this deliberately stays dependency-free (Node
 * built-ins only: readline/promises, native fetch, os, fs).
 *
 * Scope is intentionally narrow: Tenant ID + Client ID only, written to
 * frontend/.env.local in the same shape frontend/.env.example documents.
 * LAN IP / mkcert HTTPS cert setup remain manual IT steps — this script
 * only passively detects the LAN IP to remind the user which Redirect URIs
 * need registering in their Entra App Registration.
 *
 * VITE_MSAL_REDIRECT_URI is deliberately never written here — msalConfig.ts
 * already falls back to window.location.origin, and touching that value is
 * out of scope for this wizard.
 */

import { createInterface } from 'node:readline/promises';
import { stdin, stdout } from 'node:process';
import { existsSync, writeFileSync } from 'node:fs';
import { networkInterfaces } from 'node:os';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ENV_LOCAL_PATH = path.resolve(__dirname, '../frontend/.env.local');

const GUID_RE = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;

const rl = createInterface({ input: stdin, output: stdout });

// Deliberately NOT repeated rl.question() calls — when stdin is piped rather
// than an interactive TTY, each question() only registers its 'line' listener
// at call time, so a line that arrives (or was already buffered) before that
// registration is silently dropped, and every question after the first hangs
// forever. Pulling from the interface's own async iterator instead queues
// lines correctly regardless of timing. Confirmed by direct repro during
// this feature's own verification pass — real interactive terminal use
// wasn't otherwise going to surface this, but automated/piped testing was.
const lines = rl[Symbol.asyncIterator]();

async function prompt(question) {
  stdout.write(question);
  const { value } = await lines.next();
  return (value ?? '').trim();
}

/**
 * Checks a Tenant ID against Microsoft's unauthenticated OpenID discovery
 * endpoint. HTTP 200 = tenant exists; HTTP 400's JSON body carries a
 * human-readable AADSTS<code> error_description we surface directly rather
 * than inventing our own generic message.
 */
async function validateTenantId(tenantId) {
  const url = `https://login.microsoftonline.com/${encodeURIComponent(tenantId)}/v2.0/.well-known/openid-configuration`;
  let res;
  try {
    res = await fetch(url);
  } catch (err) {
    return { ok: false, reason: `Network error reaching Microsoft: ${err instanceof Error ? err.message : String(err)}` };
  }
  if (res.ok) return { ok: true };
  let body;
  try {
    body = await res.json();
  } catch {
    return { ok: false, reason: `Unexpected response from Microsoft (HTTP ${res.status})` };
  }
  return { ok: false, reason: body?.error_description || `HTTP ${res.status}` };
}

function isValidGuid(value) {
  return GUID_RE.test(value);
}

/** Non-internal IPv4 addresses only — no shelling out to ipconfig/ifconfig. */
function detectLanIPv4Addresses() {
  const nets = networkInterfaces();
  const addrs = [];
  for (const iface of Object.values(nets)) {
    if (!iface) continue;
    for (const addr of iface) {
      if (addr.family === 'IPv4' && !addr.internal) {
        addrs.push(addr.address);
      }
    }
  }
  return addrs;
}

async function main() {
  console.log('=== Quality Inspection v4.0 — Azure/Entra Setup ===\n');

  if (existsSync(ENV_LOCAL_PATH)) {
    const answer = await prompt('A config file already exists at frontend/.env.local. Overwrite? (y/n): ');
    if (answer.toLowerCase() !== 'y') {
      console.log('\nSetup cancelled. Existing frontend/.env.local left untouched.');
      rl.close();
      return;
    }
    console.log('');
  }

  let tenantId = '';
  for (;;) {
    tenantId = await prompt('Enter your Azure AD Tenant ID: ');
    process.stdout.write('  Checking with Microsoft...\n');
    const result = await validateTenantId(tenantId);
    if (result.ok) break;
    console.log(`  ✗ Invalid Tenant ID — ${result.reason}\n`);
  }
  console.log('  ✔ Tenant ID verified.\n');

  let clientId = '';
  for (;;) {
    clientId = await prompt('Enter your Azure AD Application (Client) ID: ');
    if (isValidGuid(clientId)) break;
    console.log('  ✗ Invalid Client ID — must be a valid GUID (8-4-4-4-12 hex format), e.g. 12345678-1234-1234-1234-123456789abc\n');
  }
  console.log('');

  const envContent = `# Microsoft Entra ID / MSAL.js — real credentials (NAVIGATION_AND_RBAC.md §3.1).
# Generated by \`npm run setup\`. Re-run \`npm run setup\` to overwrite.
# App Registration type: SPA, no client secret.
VITE_MSAL_CLIENT_ID=${clientId}
VITE_MSAL_TENANT_ID=${tenantId}
`;

  writeFileSync(ENV_LOCAL_PATH, envContent, 'utf8');

  console.log('✔ Setup complete — frontend/.env.local has been written.\n');
  console.log('Next steps:');
  console.log('  1. Run `npm run dev` (or restart the dev server if it\'s already running).');
  console.log('     Vite only reads .env.local when its process starts — it will NOT pick');
  console.log('     up these values without a restart.');
  console.log('  2. The first person to open the app becomes the first admin via the');
  console.log('     existing bootstrap-admin screen — no further setup needed here.');

  const lanIPs = detectLanIPv4Addresses();
  const redirectUris = ['https://localhost:4001', ...lanIPs.map((ip) => `https://${ip}:4001`)];
  console.log('  3. Confirm these Redirect URIs are registered in your Entra App Registration:');
  for (const uri of redirectUris) {
    console.log(`     - ${uri}`);
  }

  rl.close();
}

main();
